%% DYNAMIC MODEL IN TERMS OF ERROR WITH RESPECT TO ROAD
R = 10;  % radious of the road
Caf = 222685.8 / 2; % Cornering stiffnes az első kerékhez
Car = 136242.8 / 2; % Cornering stiffnes a hátsó kerékhez
lf = 1236e-3; % Az autó tömegközéppontjától mért elülső tengelytáv
lr = 2789e-3 - lf; % Az autó tömegközéppontjától mért hátsó tengelytáv
m = 2300; % Az autó tömege
vx = 10; % Az autó haladási sebessége a saját koordinátarendszerében
Iz = 2873; % Az autó tehetetlenségi nyomatéka
b = 50;

%Contious time state space model  
A_check = [0 1                            0                      0                           0;...
     0 -(2*Caf+2*Car)/(m*vx)        (2*Caf+2*Car)/m        (-2*lf*Caf+2*lr*Car)/(m*vx) 0;...
     0 0                            0                      1                           0;...
     0 -(2*lf*Caf-2*lr*Car)/(Iz*vx) (2*lf*Caf-2*lr*Car)/Iz -(2*lf*lf*Caf+2*lr*lr*Car)/(Iz*vx) 0;...
     0 0                            0                      0                           -b/m];
% Desired yaw rate as disturbance from road radius Vx/R
Bd_check = [0;...
     -(2*lf*Caf-2*lr*Car)/(m*Vx)-Vx;...
     0;...
     -(2*lf*lf*Caf+2*lr*lr*Car)/(Iz*Vx);...
     0];
%% LPV matrices
A0 = [0 1 0                      0 0;...
      0 0 (2*Caf+2*Car)/m        0 0;...
      0 0 0                      1 0;...
      0 0 (2*lf*Caf-2*lr*Car)/Iz 0 0;...
      0 0 0                      0 -b/m];
A1 = [0 0                         0 0                                 0;...
      0 -(2*Caf+2*Car)/m          0 (-2*lf*Caf+2*lr*Car)/m            0;...
      0 0                         0 0                                 0;...
      0 -(2*lf*Caf-2*lr*Car)/Iz   0 -(2*lf*lf*Caf+2*lr*lr*Car)/Iz     0;...
      0 0                         0 0                                 0];
A = A0 + (1/vx)*A1
% Steering angle as input
Bc1 =[0;...
      2*Caf/m;...
      0;...
      2*lf*Caf/Iz;...
      0];
% Force as input
Bc2 =  [0;
        0;
        0;
        0;
        1/m];

Bd1 = [0;...
       -(2*lf*Caf-2*lr*Car)/m;...
       0;...
       -(2*lf*lf*Caf+2*lr*lr*Car)/Iz;...
       0];
Bd2 = [0;...
       -1;...
       0;...
       0;...
       0];
Bd = (1/Vx) * Bd1 + Vx * Bd2;

% Outputs are lateral position error and longitudinal velocity
C = [1 0 0 0 1];

c_ss = ss(A,[Bc1 Bc2 Bd],C,0);
% Discretise state space model
